### ISSUE TITLE
IntelliJ plugin with Perforce changes name of changelist

### ISSUE THREAD

**Issue by robfreundlich** [4ch1m/ChangelistOrganizer#2]
When the plugin moves things into a changelist, it changes the name and description of that changelist to "Created by 'Changelist Organizer' instead of leaving it alone. That's a problem, since I am using a very specific naming/description scheme for my changelists, including adding a p4nits tag to some of them to prevent them from accidentally being checked in.

I'm using IntelliJ IDEA 2021.2 with Perforce, and Changelist Organizer Plugin 1.9

**Comment by 4ch1m** [comment]
The string `Created by 'Changelist Organizer'` only gets inserted as the changelist _comment_ (when created by the plugin) **not** the changelist _name_:

```
LocalChangeList localChangeList = changeListManager.addChangeList(changelistOrganizerItem.getChangeListName(), ChangelistOrganizerStrings.message("organize.changelist.comment"));
```
see: [ChangelistOrganizer.java](https://github.com/4ch1m/ChangelistOrganizer/blob/3b914f0f47e46b39aa87eb211a0c2040833a29f0/src/main/java/de/achimonline/changelistorganizer/ChangelistOrganizer.java#L51)
also see: [changelistorganizer.properties](https://github.com/4ch1m/ChangelistOrganizer/blob/3b914f0f47e46b39aa87eb211a0c2040833a29f0/src/main/resources/de/achimonline/changelistorganizer/changelistorganizer.properties#L22)

The actual name of the changelist should remain as defined in the project settings.

Could you provide a screenshot showing your issue?

**Comment by robfreundlich** [comment]
I can't reproduce this now. I wonder if maybe I had a subtly typo in the name I was giving to ChangelistOrganizer, and so it was creating a new changelist, or something like that.

**Comment by 4ch1m** [comment]
@RobFreundlich could you please update/delete your review of my plugin on [plugins.jetbrains.com](https://plugins.jetbrains.com/plugin/9216-changelist-organizer/reviews) since what you wrote is definitely not true!
Thanks.

**Comment by robfreundlich** [comment]
Hi, Achim,

Sorry to be so long responding to this. I've had a crazy couple of months.

I was going to say that I'm still having the problem I described in the
review, but I just double-checked my rules, and realized I have a typo in
the changelist name that I'm expecting things to go into! So yes, I'll
update the review.

Cheers,
Rob
